# Generated by Django 4.2.1 on 2024-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('primary_email', models.EmailField(default='', max_length=100)),
                ('secondary_email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('has_acknowledged_faq', models.BooleanField(default=False)),
                ('requested_access', models.BooleanField(default=False)),
                ('requested_surrender', models.BooleanField(default=False)),
                ('alert_on_date', models.DateField(blank=True, null=True)),
                ('email_signature', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
