# Generated by Django 4.2.1 on 2024-12-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_userprofile_primary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_level',
            field=models.IntegerField(choices=[(0, 'Adopter'), (1, 'Greeter'), (2, 'Admin'), (3, 'Superuser')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
