# Generated by Django 5.1.4 on 2024-12-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_cats_in_home_userprofile_dogs_in_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cats_in_home',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dogs_in_home',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='other_pets_comment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='other_pets_in_home',
        ),
    ]
