# Generated by Django 5.1.4 on 2024-12-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_cats_in_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobility',
        ),
    ]
