# Generated by Django 5.1.4 on 2024-12-28 17:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_mobility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alert_on_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adoption_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_otp_try',
            field=models.CharField(default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 28, 12, 30, 9, 729265)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_email',
            field=models.EmailField(default='', max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
