# Generated by Django 5.1.4 on 2025-01-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_adopter_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['first_name', 'last_name', 'primary_email']},
        ),
    ]
