# Generated by Django 5.1.4 on 2025-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
