# Generated by Django 5.1.4 on 2026-02-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_userprofile_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="street_address",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
