# Generated by Django 5.1.4 on 2026-07-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_postal_code_userprofile_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='security_level',
            field=models.IntegerField(choices=[(0, 'Adopter'), (1, 'Greeter'), (2, 'Admin'), (3, 'Superuser'), (4, 'Dashboard')]),
        ),
    ]
