# Generated by Django 5.1.4 on 2026-02-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopters", "0012_alter_adopter_gender_preference_and_more"),
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="age_months",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="available_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="description",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="dog",
            name="fun_size",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dog",
            name="interest_adopters",
            field=models.ManyToManyField(to="adopters.adopter"),
        ),
        migrations.AddField(
            model_name="dog",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="dog",
            name="photo_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="dog",
            name="sex",
            field=models.IntegerField(choices=[(0, "Female"), (1, "Male")], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dog",
            name="shelterluv_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dog",
            name="weight",
            field=models.IntegerField(null=True),
        ),
    ]
