# Generated by Django 5.1.4 on 2026-02-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_age_months_dog_available_date_dog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='available_now',
            field=models.BooleanField(default=True),
        ),
    ]
