# Generated by Django 5.1.4 on 2026-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_dog_available_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="age_months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="available_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
