# Generated by Django 5.1.4 on 2026-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_alter_dog_age_months_alter_dog_available_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="breed",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
