# Generated by Django 5.1.4 on 2026-02-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopters", "0012_alter_adopter_gender_preference_and_more"),
        ("dogs", "0005_dog_breed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="interest_adopters",
            field=models.ManyToManyField(blank=True, null=True, to="adopters.adopter"),
        ),
    ]
