# Generated by Django 5.1.4 on 2026-02-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_alter_dog_interest_adopters'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='unavailable_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
