# Generated by Django 5.1.4 on 2026-03-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0008_dog_unavailable_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="available_now",
        ),
        migrations.AddField(
            model_name="dog",
            name="publishable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Available Now"),
                    (1, "Chosen_SN"),
                    (2, "Chosen_WC"),
                    (3, "FTA"),
                    (4, "Healthy in Home"),
                    (5, "Unavailable"),
                ],
                default=5,
            ),
            preserve_default=False,
        ),
    ]
