# Generated by Django 5.1.4 on 2026-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_remove_dog_available_now_dog_publishable_dog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='last_intake',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
