# Generated by Django 5.1.4 on 2026-04-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_dog_last_intake_dog_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='other_photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
