# Generated by Django 5.1.4 on 2026-06-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0011_dog_other_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available Now'), (1, 'Chosen_SN'), (2, 'Chosen_WC'), (3, 'FTA'), (4, 'Healthy in Home'), (5, 'Unavailable'), (6, 'Foster')]),
        ),
    ]
