# Generated by Django 5.1.4 on 2025-01-01 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pending_adoptions', '0005_alter_pendingadoption_source_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAdoptionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Cough'), (1, 'Nasal Discharge'), (2, 'Other')])),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='pending_adoptions.pendingadoption')),
            ],
        ),
    ]
