# Generated by Django 5.1.4 on 2024-12-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingadoption',
            name='circumstance',
            field=models.IntegerField(choices=[(0, 'Host Weekend'), (1, 'Foster'), (2, 'Appointment'), (3, 'Friend of Foster'), (4, 'Friend of Molly'), (5, 'Other')]),
        ),
    ]
