# Generated by Django 5.1.4 on 2024-12-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_outcome'),
        ('pending_adoptions', '0002_alter_pendingadoption_circumstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingadoption',
            name='source_appointment_admin',
        ),
        migrations.AddField(
            model_name='pendingadoption',
            name='heartworm_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingadoption',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chosen'), (1, 'Needs Vetting'), (2, 'Needs Well Check'), (3, 'Ready'), (4, 'Completed'), (5, 'Canceled')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingadoption',
            name='paperwork_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_adoption_paperwork', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='pendingadoption',
            name='source_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_adoption', to='appointments.appointment'),
        ),
    ]
