# Generated by Django 5.1.4 on 2024-12-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_appointment_notes_and_more'),
        ('pending_adoptions', '0003_remove_pendingadoption_source_appointment_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingadoption',
            name='paperwork_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paperwork_adoption', to='appointments.appointment'),
        ),
    ]
