# Generated by Django 5.1.4 on 2024-12-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_appointment_notes_and_more'),
        ('pending_adoptions', '0004_alter_pendingadoption_paperwork_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingadoption',
            name='source_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_adoption', to='appointments.appointment'),
        ),
    ]
