# Generated by Django 5.1.4 on 2025-01-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_adoptions', '0005_alter_pendingadoption_source_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingadoption',
            name='circumstance',
            field=models.IntegerField(choices=[(0, 'Host Weekend'), (1, 'Foster'), (2, 'Appointment'), (6, 'Open House'), (3, 'Friend of Foster'), (4, 'Friend of Molly'), (5, 'Other')]),
        ),
        migrations.AlterField(
            model_name='pendingadoption',
            name='created_instant',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
