# Generated by Django 5.1.4 on 2026-02-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pending_adoptions", "0006_alter_pendingadoption_circumstance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingadoption",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Chosen"),
                    (1, "Needs Vetting"),
                    (2, "Needs Well Check"),
                    (3, "Ready to Roll"),
                    (4, "Completed"),
                    (5, "Canceled"),
                ]
            ),
        ),
    ]
