# Generated by Django 5.1.4 on 2026-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_adoptions', '0007_alter_pendingadoption_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingadoption',
            name='dogID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
