# Generated by Django 5.1.4 on 2026-04-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_adoptions', '0008_pendingadoption_dogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingadoption',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chosen'), (1, 'Needs Spay/Neuter'), (2, 'Needs Well Check'), (3, 'Ready to Roll'), (4, 'Completed'), (5, 'Canceled')]),
        ),
    ]
