# Generated by Django 4.2.1 on 2024-07-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortNoticeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Add'), (1, 'Change'), (2, 'Cancel')])),
                ('source_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='short_notice_cancel', to='bookings.booking')),
                ('target_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='short_notice_schedule', to='bookings.booking')),
            ],
        ),
    ]
