# Generated by Django 5.1.4 on 2025-01-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fta_doc_1', models.FileField(blank=True, null=True, upload_to='')),
                ('fta_doc_2', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
