# Generated by Django 5.1.4 on 2025-01-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsettings',
            name='default_sending_email',
            field=models.EmailField(default='sheltercenterdev@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentsettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentsettings',
            name='environment_type',
            field=models.IntegerField(choices=[(0, 'Production'), (1, 'Test'), (2, 'Development')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentsettings',
            name='test_recipient_email',
            field=models.EmailField(default='sheltercenterdev@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
