# Generated by Django 5.1.4 on 2025-01-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_settings', '0003_alter_environmentsettings_fta_doc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsettings',
            name='fta_doc_1_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='environmentsettings',
            name='fta_doc_2_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
