# Generated by Django 5.1.4 on 2025-01-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment_settings', '0004_environmentsettings_fta_doc_1_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentsettings',
            name='fta_doc_1',
        ),
        migrations.RemoveField(
            model_name='environmentsettings',
            name='fta_doc_2',
        ),
    ]
