# Generated by Django 5.1.4 on 2025-01-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_settings', '0005_remove_environmentsettings_fta_doc_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentsettings',
            name='environment_type',
            field=models.IntegerField(choices=[(0, 'Production'), (1, 'Test'), (2, 'Development'), (3, 'Staging')]),
        ),
    ]
