# Generated by Django 5.1.4 on 2026-02-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_settings', '0006_alter_environmentsettings_environment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsettings',
            name='last_dog_import',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
