# Generated by Django 5.1.4 on 2026-06-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_settings', '0007_environmentsettings_last_dog_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsettings',
            name='application_approved_pdf_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
