# Generated by Django 4.2.1 on 2024-07-14 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Approved'), (1, 'Pending'), (2, 'Declined')])),
                ('shelterluv_app_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('shelterluv_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('approved_until', models.DateField()),
                ('homeowner', models.IntegerField(blank=True, choices=[(0, 'Own'), (1, 'Rent'), (2, 'Live With Parents')], null=True)),
                ('houseing_type', models.IntegerField(blank=True, choices=[(0, 'House'), (1, 'Apartment'), (2, 'Condo'), (3, 'Townhouse'), (4, 'Dorm'), (5, 'Mobile Home')], null=True)),
                ('activity_level', models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Moderate'), (2, 'Active'), (3, 'Very Active')], null=True)),
                ('has_fence', models.BooleanField(default=False)),
                ('application_comments', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to='users.userprofile')),
            ],
        ),
    ]
