# Generated by Django 5.1.4 on 2024-12-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0002_remove_adopter_user_adopter_primary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='internal_notes',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
