# Generated by Django 5.1.4 on 2024-12-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0004_adopter_adopter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='bringing_dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='cats_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='dogs_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='mobility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='other_pets_comment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='other_pets_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
