# Generated by Django 5.1.4 on 2024-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0006_rename_houseing_type_adopter_housing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='low_allergy',
            field=models.BooleanField(default=False),
        ),
    ]
