# Generated by Django 5.1.4 on 2024-12-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0007_adopter_low_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='age_preference',
            field=models.IntegerField(blank=True, choices=[(0, 'Adults'), (1, 'Puppies'), (2, 'No Preference')], null=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='gender_preference',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'No Preference')], null=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='max_weight_preference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='min_weight_preference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
