# Generated by Django 5.1.4 on 2024-12-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0008_adopter_age_preference_adopter_gender_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='last_uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
