# Generated by Django 5.1.4 on 2025-01-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0010_remove_adopter_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopter',
            options={'ordering': ['user_profile', 'primary_email']},
        ),
        migrations.AddField(
            model_name='adopter',
            name='approval_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
