# Generated by Django 5.1.4 on 2026-02-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopters", "0011_alter_adopter_options_adopter_approval_emailed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adopter",
            name="gender_preference",
            field=models.IntegerField(
                blank=True, choices=[(0, "Males"), (1, "Females"), (2, "No Preference")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="adopter",
            name="homeowner",
            field=models.IntegerField(
                blank=True, choices=[(0, "Own"), (1, "Rent"), (2, "Live with Parents")], null=True
            ),
        ),
    ]
