# Generated by Django 5.1.4 on 2026-07-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0013_rename_low_allergy_adopter_low_shedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='activity_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Medium'), (2, 'Active'), (3, 'Very Active')], null=True),
        ),
    ]
