# Generated by Django 5.1.4 on 2026-08-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0014_alter_adopter_activity_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterUploadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelterluv_app_id', models.CharField(blank=True, default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_events', to='adopters.adopter')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
