# Generated by Django 5.1.4 on 2026-08-16 17:17

from django.db import migrations


def seed_upload_events(apps, _schema_editor):
    Adopter = apps.get_model("adopters", "Adopter")
    AdopterUploadEvent = apps.get_model("adopters", "AdopterUploadEvent")
    events = []
    for adopter in Adopter.objects.filter(last_uploaded__isnull=False):
        events.append(
            AdopterUploadEvent(
                adopter=adopter,
                shelterluv_app_id=adopter.shelterluv_app_id or "",
                uploaded_at=adopter.last_uploaded,
            )
        )
    AdopterUploadEvent.objects.bulk_create(events)


class Migration(migrations.Migration):

    dependencies = [
        ("adopters", "0015_adopter_upload_event"),
    ]

    operations = [
        migrations.RunPython(seed_upload_events, migrations.RunPython.noop),
    ]
