# Generated by Django 4.2.1 on 2024-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Paperwork'), (1, 'Surrender'), (2, 'Host Weekend Chosen'), (3, 'Donation Drop Off')])),
                ('subtype', models.IntegerField(blank=True, choices=[(0, 'Adoption'), (1, 'Fta')], null=True)),
                ('instant', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
