# Generated by Django 5.1.4 on 2024-12-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminappointment',
            name='type',
            field=models.IntegerField(choices=[(3, 'Paperwork'), (4, 'Surrender'), (5, 'Visit'), (6, 'Donation Drop Off')]),
        ),
    ]
