# Generated by Django 4.2.1 on 2024-10-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booking',
        ),
    ]
