# Generated by Django 5.1.4 on 2024-12-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_subtype_alter_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
