# Generated by Django 5.1.4 on 2024-12-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_soft_deleted'),
    ]

    operations = [
    ]
