# Generated by Django 5.1.4 on 2024-12-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_soft_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
