# Generated by Django 5.1.4 on 2024-12-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.IntegerField(blank=True, choices=[(0, 'Adoption'), (1, 'Fta'), (2, 'Chosen'), (3, 'No Decision'), (4, 'Noshow')], null=True),
        ),
    ]
