# Generated by Django 5.1.4 on 2024-12-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='outcome',
            field=models.IntegerField(blank=True, choices=[(0, 'Adoption'), (1, 'Fta'), (2, 'Chosen'), (3, 'No Decision'), (4, 'No Show')], null=True),
        ),
    ]
