# Generated by Django 5.1.4 on 2024-12-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_notes',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counselor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
