# Generated by Django 5.1.4 on 2025-01-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='surrendered_dog',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='surrendered_dog_fka',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
