# Generated by Django 5.1.4 on 2025-01-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointment_surrendered_dog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chosen_dog',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
