# Generated by Django 5.1.4 on 2025-12-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_chosen_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Adults'), (1, 'Puppies'), (2, 'All Ages and Sizes'), (3, 'Paperwork'), (4, 'Surrender'), (5, 'Visit'), (6, 'Donation Drop-Off'), (7, 'Fun-Size')]),
        ),
    ]
