# Generated by Django 5.1.4 on 2026-05-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chosen_dog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
