# Generated by Django 5.1.4 on 2026-08-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_populate_chosen_dog_id'),
        ('dogs', '0012_alter_dog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='surrendered_dog_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surrender_appointments', to='dogs.dog'),
        ),
    ]
