# Generated by Django 4.2.1 on 2024-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Daily'), (1, 'Internal'), (2, 'Static')])),
                ('content', models.CharField(default='', max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
