# Generated by Django 4.2.1 on 2024-08-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbase',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Mondays'), (1, 'Tuesdays'), (2, 'Wednesdays'), (3, 'Thursdays'), (4, 'Fridays'), (5, 'Saturdays'), (6, 'Sundays')]),
        ),
    ]
