# Generated by Django 5.1.4 on 2024-12-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_bases', '0002_alter_appointmentbase_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbase',
            name='subtype',
            field=models.IntegerField(blank=True, choices=[(0, 'Adoption'), (1, 'Fta')], null=True),
        ),
    ]
