# Generated by Django 5.1.4 on 2025-01-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_bases', '0006_remove_appointmentbase_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbase',
            name='type',
            field=models.IntegerField(choices=[(0, 'Adults'), (1, 'Puppies'), (2, 'All Ages'), (3, 'Paperwork'), (4, 'Surrender'), (5, 'Visit'), (6, 'Donation Drop-Off'), (7, 'Fun-Size')]),
        ),
    ]
