# Generated by Django 5.1.4 on 2026-02-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment_bases", "0007_alter_appointmentbase_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentbase",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Adults"),
                    (1, "Puppies"),
                    (2, "All Ages and Sizes"),
                    (3, "Paperwork"),
                    (4, "Surrender"),
                    (5, "Visit"),
                    (6, "Donation Drop-Off"),
                    (7, "Fun-Size"),
                ]
            ),
        ),
    ]
