# Generated by Django 4.2.1 on 2024-08-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Cancelled'), (2, 'Rescheduled'), (3, 'Completed'), (4, 'Noshow')], default=1),
            preserve_default=False,
        ),
    ]
