# Generated by Django 4.2.1 on 2024-10-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking',
            new_name='appointment',
        ),
    ]
