# Generated by Django 5.1.4 on 2024-12-22 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_booking_booking_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 0, 1, 42, 712576)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
