# Generated by Django 5.1.4 on 2024-12-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0006_rename_houseing_type_adopter_housing_type'),
        ('appointments', '0004_appointment_soft_deleted'),
        ('bookings', '0006_booking_created_booking_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='adopters.adopter'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='appointments.appointment'),
        ),
    ]
