# Generated by Django 5.1.4 on 2025-03-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_adopter_alter_booking_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sent_dogs_not_here_yet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_dogs_were_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_limited_fun_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_limited_hypo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_limited_puppies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_limited_small_puppies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_x_in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
