# Generated by Django 5.1.4 on 2026-02-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_sent_dogs_not_here_yet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Active"),
                    (1, "Cancelled"),
                    (2, "Rescheduled"),
                    (3, "Completed"),
                    (4, "No Show"),
                ]
            ),
        ),
    ]
