# Generated by Django 5.1.4 on 2026-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_cancel_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'booking'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Cancelled'), (2, 'Rescheduled'), (3, 'Completed'), (4, 'No Show')], db_index=True),
        ),
    ]
